name        = "AllinOne"
license     = "MIT"
licenselink = "https://github.com/orianna-zzo/AllinOne/blob/master/LICENSE"
description = "All you need of a blog in one template."
homepage    = "https://github.com/orianna-zzo/AllinOnee"

[author]
  name      = "ZHENG Zi'ou"
  homepage  = "https://github.com/orianna-zzo"
